steps:
  # 1. Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '--progress=plain',
      '--no-cache',
      '-t', 'handwriting-synthesis:latest',
      '-t', 'asia-northeast3-docker.pkg.dev/${PROJECT_ID}/handwriting-synthesis-service-images/handwriting-synthesis:latest',
      '-t', 'us-west2-docker.pkg.dev/${PROJECT_ID}/handwriting-synthesis-service-images/handwriting-synthesis:latest',
      '-t', 'us-east4-docker.pkg.dev/${PROJECT_ID}/handwriting-synthesis-service-images/handwriting-synthesis:latest',
      '.'
    ]

  # 2. Push images to registries
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-asia'
    args: ['push', 'asia-northeast3-docker.pkg.dev/${PROJECT_ID}/handwriting-synthesis-service-images/handwriting-synthesis:latest']
    
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-us-west'
    args: ['push', 'us-west2-docker.pkg.dev/${PROJECT_ID}/handwriting-synthesis-service-images/handwriting-synthesis:latest']
    
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-us-east'
    args: ['push', 'us-east4-docker.pkg.dev/${PROJECT_ID}/handwriting-synthesis-service-images/handwriting-synthesis:latest']

  # 3. Deploy to Cloud Run in different regions
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-asia'
    waitFor: ['push-asia']
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'handwriting-synthesis-asia-northeast3'
      - '--image'
      - 'asia-northeast3-docker.pkg.dev/${PROJECT_ID}/handwriting-synthesis-service-images/handwriting-synthesis:latest'
      - '--region'
      - 'asia-northeast3'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--service-account'
      - '334167120222-compute@developer.gserviceaccount.com'
      - '--port'
      - '8000'
      - '--cpu'
      - '8'
      - '--memory'
      - '32Gi'
      
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-us-west'
    waitFor: ['push-us-west']
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'handwriting-synthesis-us-west2'
      - '--image'
      - 'us-west2-docker.pkg.dev/${PROJECT_ID}/handwriting-synthesis-service-images/handwriting-synthesis:latest'
      - '--region'
      - 'us-west2'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--service-account'
      - '334167120222-compute@developer.gserviceaccount.com'
      - '--port'
      - '8000'
      - '--cpu'
      - '8'
      - '--memory'
      - '32Gi'
      
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-us-east'
    waitFor: ['push-us-east']
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'handwriting-synthesis-us-east4'
      - '--image'
      - 'us-east4-docker.pkg.dev/${PROJECT_ID}/handwriting-synthesis-service-images/handwriting-synthesis:latest'
      - '--region'
      - 'us-east4'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--service-account'
      - '334167120222-compute@developer.gserviceaccount.com'
      - '--port'
      - '8000'
      - '--cpu'
      - '8'
      - '--memory'
      - '32Gi'

  # 4. Restart VMs to trigger startup script
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'restart-vm-asia'
    waitFor: ['push-asia']
    entrypoint: gcloud
    args:
      - 'compute'
      - 'instances'
      - 'reset'
      - 'handwriting-synthesis-vm-asia-northeast3'
      - '--zone=asia-northeast3-a'

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'restart-vm-us-west'
    waitFor: ['push-us-west']
    entrypoint: gcloud
    args:
      - 'compute'
      - 'instances'
      - 'reset'
      - 'handwriting-synthesis-vm-us-west2'
      - '--zone=us-west2-a'

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'restart-vm-us-east'
    waitFor: ['push-us-east']
    entrypoint: gcloud
    args:
      - 'compute'
      - 'instances'
      - 'reset'
      - 'handwriting-synthesis-vm-us-east4'
      - '--zone=us-east4-a'

options:
  logging: CLOUD_LOGGING_ONLY

images:
  - 'asia-northeast3-docker.pkg.dev/${PROJECT_ID}/handwriting-synthesis-service-images/handwriting-synthesis:latest'
  - 'us-west2-docker.pkg.dev/${PROJECT_ID}/handwriting-synthesis-service-images/handwriting-synthesis:latest'
  - 'us-east4-docker.pkg.dev/${PROJECT_ID}/handwriting-synthesis-service-images/handwriting-synthesis:latest'