steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build',
           '--progress=plain',
           '--no-cache',
           '-t', 'us-central1-docker.pkg.dev/optimum-rock-447312-u8/waiter-images/handwriting-synthesis:latest',
           '.']

  # Push the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/optimum-rock-447312-u8/waiter-images/handwriting-synthesis:latest']

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'handwriting-synthesis'
      - '--image'
      - 'us-central1-docker.pkg.dev/optimum-rock-447312-u8/waiter-images/handwriting-synthesis:latest'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--service-account'
      - '334167120222-compute@developer.gserviceaccount.com'
      - '--port'
      - '8000'

options:
  logging: CLOUD_LOGGING_ONLY

images:
  - 'us-central1-docker.pkg.dev/optimum-rock-447312-u8/waiter-images/handwriting-synthesis:latest' 