steps:
  # Build and push the handwriting synthesis service
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/handwriting-synthesis:$COMMIT_SHA', '-f', 'Dockerfile', '.']

  # Build and push the handwriting quality service
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/handwriting-quality:$COMMIT_SHA', '-f', 'Dockerfile.gemini', '.']

  # Push the images
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/handwriting-synthesis:$COMMIT_SHA']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/handwriting-quality:$COMMIT_SHA']

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'handwriting-synthesis'
      - '--image'
      - 'gcr.io/$PROJECT_ID/handwriting-synthesis:$COMMIT_SHA'
      - '--region'
      - 'asia-northeast3'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'handwriting-quality'
      - '--image'
      - 'gcr.io/$PROJECT_ID/handwriting-quality:$COMMIT_SHA'
      - '--region'
      - 'asia-northeast3'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'

images:
  - 'gcr.io/$PROJECT_ID/handwriting-synthesis:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/handwriting-quality:$COMMIT_SHA'