options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # Build and push the handwriting synthesis service
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/handwriting-synthesis:$COMMIT_SHA', '-f', 'Dockerfile', '.']

  # Build and push the handwriting quality service
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/handwriting-quality:$COMMIT_SHA', '-f', 'Dockerfile.gemini', '.']

  # Push the images
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/handwriting-synthesis:$COMMIT_SHA']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/handwriting-quality:$COMMIT_SHA']

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'handwriting-synthesis'
      - '--image'
      - 'gcr.io/$PROJECT_ID/handwriting-synthesis:$COMMIT_SHA'
      - '--region'
      - 'asia-northeast3'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '2Gi'
      - '--cpu'
      - '2'
      - '--min-instances'
      - '1'
      - '--max-instances'
      - '10'
      - '--set-env-vars'
      - 'GEMINI_SERVICE_URL=https://handwriting-quality-${PROJECT_ID}.a.run.app'
      - '--set-secrets'
      - 'GOOGLE_API_KEY=GOOGLE_API_KEY:latest'
      - '--command'
      - 'uvicorn'
      - '--args'
      - 'main:app,--host=0.0.0.0,--port=8080,--workers=1,--log-level=info'

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'handwriting-quality'
      - '--image'
      - 'gcr.io/$PROJECT_ID/handwriting-quality:$COMMIT_SHA'
      - '--region'
      - 'asia-northeast3'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '1Gi'
      - '--cpu'
      - '1'
      - '--min-instances'
      - '1'
      - '--max-instances'
      - '5'
      - '--set-secrets'
      - 'GOOGLE_API_KEY=GOOGLE_API_KEY:latest'
      - '--command'
      - 'uvicorn'
      - '--args'
      - 'gemini_image_compare:app,--host=0.0.0.0,--port=5000,--workers=1,--log-level=info'

images:
  - 'gcr.io/$PROJECT_ID/handwriting-synthesis:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/handwriting-quality:$COMMIT_SHA'