version: '3.8'

services:
  handwriting-synthesis:
    build:
      context: .
      dockerfile: Dockerfile.hwr_api
    ports:
      - "8080:8080"
    volumes:
      - ./styles:/app/styles
      - ./checkpoints:/app/checkpoints
      - ./debug_logs:/app/debug_logs
      - ./output:/app/output
      - .:/app
    environment:
      - CLOUD_RUN_REGION=${CLOUD_RUN_REGION:-unknown}
      - HOSTNAME=${HOSTNAME:-unknown}
      - K_REVISION=${K_REVISION:-unknown}
      - GEMINI_SERVICE_URL=http://handwriting-quality:5000
      - UVICORN_RELOAD=true
      - UVICORN_RELOAD_DIRS=/app
    networks:
      - handwriting-network
      - external-network
    depends_on:
      - handwriting-quality
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    restart: unless-stopped
    runtime: nvidia 
    deploy:
      resources:
        limits:
          cpus: '8'
          memory: 8G
        reservations:
          cpus: '4'
          memory: 5G

  handwriting-quality:
    build:
      context: .
      dockerfile: Dockerfile.gemini
    expose:
      - "5000"
    environment:
      - GOOGLE_API_KEY=AIzaSyDivuZiJD_A2ba9l5nuZHT8gqyeSY2jmkY
    volumes:
      - ./temp:/tmp
    networks:
      - handwriting-network
      - external-network
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 10G
        reservations:
          cpus: '4'
          memory: 5G

networks:
  handwriting-network:
    driver: bridge
    internal: true
  external-network:
    driver: bridge
